### ISSUE TITLE
How to used -o/-ordinary short_reads.fa

### ISSUE THREAD

**Issue by tiramisutes** [lanl001/HiBAM#1]
I have many pair-end reads from different insert size library. So, how to use the ``-o/-ordinary short_reads.fa`` parameter? Merged all this pair-end fasta reads  into a whole?

**Comment by lanl001** [comment]
Yes. For each file of paired-end reads, you should firstly separate it into two files: left-end.fa and right-end.fa. Then merge all the files into a whole using cat command.

**Comment by lanl001** [comment]
Yes. For each file of paired-end reads, you should firstly separate it into two files: left-end.fa and right-end.fa. Then merge all the files into a whole using cat command.

**Comment by tiramisutes** [comment]
OK, Thanks for replying.
