### ISSUE TITLE
ERROR: -out is not a valid option.

### ISSUE THREAD

**Issue by jazberna1** [lanl001/HiBAM#3]
Hello,

I was wondering if you could please help me  with the following error I get while running HALC:
ERROR: -out is not a valid option.

which is prepended by BLASR usage.

My BLASR version is 1.3.1.124201 and does have the -out option

Many thanks
Jorge

**Comment by jazberna1** [comment]
Hi ,

It looks to me that HALC calls BLASR like this:
 --maxScore 2000 --minMatch 8 --minAlnLength 15 --nCandidates 30 --bestn 20 --nproc 12
with '--' instead of '-'

Do I need to use a specific BLASR version?

Thanks
Jorge

**Comment by lanl001** [comment]
Yes. There have been some changes in the recent version of BLASR. Try to use version 5.2 or later.

**Comment by jazberna1** [comment]
Hi,

ok, thanks, I'll do so
Jorge
